### ISSUE TITLE
[JNPCT] Improve offline dashboard cards

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jnpct#108]
https://avni.freshdesk.com/a/tickets/1370

- [x] Make improvements in the offline cards similar to what we did in SNCU
      - Check the details in this [card](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/sncu/49) to understand what kind of optimisations can be done. 
- [x] Check the current load time for the offline cards.
- [x]  Apply the fixes in dashboard code.
- [x]  Check the difference in performance and record it.
-------
- [x] High-risk ANC
- [x] Children who is in SAM grade since more than 3 months
- [x] ANC whose HB is 7 or less than 7 gm%
- [x] High risk ANC-saheli
- [x] Total SAM Children
- [x] Total MAM children
- [x] List of child death
- [x] Low birth weight children  (List of non exited and non voided children with birth weight less than 2 kg)
- [ ] Children at 7 months in SAM
- [ ] Children who died
- [ ] Children who migrated permanently
- [ ] Children with Congenital Anomaly
- [ ] Currently sick children
- [ ] At 13 months children completely immunised
- [x] Children as per red grade (0-6 months)
- [x] Children as per yellow grade (0-6 months)
- [x] Children who is not weighed since two month from SAM AND MAM grade children
- [x] Children whose kmc is ongoing
- [x] Children whose weight less than 1.8kg

Note - Make sure the changes are tested well and applied to both UAT and prod.

**Comment by sachsk** [comment]
moved the comment with checklist of reports to description

**Comment by sachsk** [comment]
these reports are not in use so not optimised 

Children at 7 months in SAM
Children who died
Children who migrated permanently
Children with Congenital Anomaly
Currently sick children
At 13 months children completely immunised

**Comment by sachsk** [comment]
Doc where old and new query present: 
https://docs.google.com/spreadsheets/d/1sTE-4CygqlIg612EYxMTBnRWKlUjU22tbvx_s42f3cA/edit?usp=sharing

**Comment by sachsk** [comment]
Not moved on Prod 
Need to test it on uat once

**Comment by Dinesh2019** [comment]
for QA purpose

High-risk ANC
 Children who is in SAM grade since more than 3 months
 ANC whose HB is 7 or less than 7 gm%
 High risk ANC-saheli
 Total SAM Children
 Total MAM children
 List of child death
 Low birth weight children (List of non exited and non voided children with birth weight less than 2 kg)
 Children at 7 months in SAM
 Children who died
 Children who migrated permanently
 Children with Congenital Anomaly
 Currently sick children
 At 13 months children completely immunised
 Children as per red grade (0-6 months)
 Children as per yellow grade (0-6 months)
 Children who is not weighed since two month from SAM AND MAM grade children
 Children whose kmc is ongoing
 Children whose weight less than 1.8kg

**Comment by Dinesh2019** [comment]
For QA purpose

- [x] Check the current load time for the offline cards.
- [x]  Apply the fixes in dashboard code.
- [x]  Check the difference in performance and record it.
-------
- [x] High-risk ANC
- [x] Children who is in SAM grade since more than 3 months
- [x] ANC whose HB is 7 or less than 7 gm%
- [x] High risk ANC-saheli
- [x] Total SAM Children
- [x] Total MAM children
- [x] List of child death
- [x] Low birth weight children  (List of non exited and non voided children with birth weight less than 2 kg)
- [ ] Children at 7 months in SAM
- [ ] Children who died
- [ ] Children who migrated permanently
- [ ] Children with Congenital Anomaly
- [ ] Currently sick children
- [ ] At 13 months children completely immunised
- [x] Children as per red grade (0-6 months)
- [x] Children as per yellow grade (0-6 months)
- [x] Children who is not weighed since two month from SAM AND MAM grade children
- [x] Children whose kmc is ongoing
- [x] Children whose weight less than 1.8kg

**Comment by Dinesh2019** [comment]
Done testing in UAT need to move to prod

**Comment by sachsk** [comment]
Before and After result 

- High-risk ANC took 124870 ms---->48465ms
- ANC whose HB is 7 or less than 7 gm% took 203820 ms------>80888ms
- Children who is in SAM grade since more than 3 months took 481365 ms------>223295ms
-  Children whose weight less than 1.8kg took 855372 ms--------->377058
- Children as per yellow grade (0-6 months) took 118630 ms---------->103319
- Children as per red grade (0-6 months) took 79572 ms---------->84492
- Total MAM children took 90108 ms---------->80939
- Total SAM Children took 133323 ms---------91311
- Children whose kmc is ongoing took 14929 ms-------->13004
- Children who is in SAM grade since more than 3 months took 131883 ms-------->116019

- Children who is not weighed since two month from SAM AND MAM grade children took 93553 ms==========>82667
- List of child death took 344 ms----->333
